export interface KitchenItem {
  id: string;
  name: string;
  category: string;
  quantity: number;
  unit: string;
  baseQuantity: number; // Jumlah dalam satuan dasar (gram/ml)
  baseUnit: 'gram' | 'ml'; // Satuan dasar untuk bahan ini
  expiryDate: string; // ISO date string
  createdAt: string;
  updatedAt: string;
}

export interface ShoppingItem {
  id: string;
  name: string;
  category: string;
  quantity: number;
  unit: string;
  baseQuantity: number; // Jumlah dalam satuan dasar (gram/ml)
  baseUnit: 'gram' | 'ml'; // Satuan dasar untuk bahan ini
  price?: number;
  isAutoGenerated: boolean;
  isPurchased: boolean;
  createdAt: string;
}

export interface MonthlyUsage {
  month: string;
  totalItems: number;
  totalValue: number;
}

export interface KitchenStats {
  totalItems: number;
  totalValue: number;
  expiringItems: number;
  categories: { [key: string]: number };
}